name: "Azure DevOps ChatOps"
description: "Integrate GitHub with Azure DevOps via ChatOps"
author: "philip-gai"
branding:
  icon: 'git-branch'  
  color: 'blue'
inputs:
  ado_domain:
    description: "The domain your ADO instance is in"
    required: true
    default: "dev.azure.com"
  ado_org:
    description: "The organization that your ADO repository is in"
    required: true
  ado_project:
    description: "The project that your ADO repository is in"
    required: true
  ado_repo:
    description: "The name of your ADO repository"
    required: true
  ado_pat:
    description: "The Personal Access Token (PAT) to use when authenticating with Azure DevOps. Use a repository secret here!"
    required: true
  github_token:
    description: "The GitHub Token to use for accessing your repos and stuff. Usually secrets.GITHUB_TOKEN"
    required: true
  default_source_branch:
    description: "The branch from which to branch from by default. This defaults to the main branch set in ADO"
    required: false
  default_target_branch_type:
    description: "The default branch type to use when none is specified. Valid values are user, users, bug, bugs, feature, features, release or releases. Default is feature"
    required: true
    default: 'feature'
runs:
  using: "node12"
  main: "dist/index.js"
