# Azure DevOps ChatOps - GitHub Action
# https://github.com/marketplace/actions/azure-devops-chatops

name: "Azure DevOps ChatOps"

on:
  issue_comment:
    types: [created]

permissions: # GITHUB_TOKEN will have the minimum permissions required to run the ChatOps
  issues: write

jobs:
  run-github-ado-chatops:
    runs-on: ubuntu-latest
    steps:
      - name: Azure DevOps ChatOps
        uses: philip-gai/github-ado-chatops@v1.0.0 # Check marketplace for the latest version
        with:
          ado_org: philip-gai # replace
          ado_project: github-ado-chatops # replace
          ado_repo: github-ado-chatops # replace
          ado_pat: ${{ secrets.ADO_PAT }} # make sure this matches the name of the secret you made
          github_token: ${{ secrets.GITHUB_TOKEN }}
