# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Node.js app - github-ado-chatops-web

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  ADO_INSTANCE: dev.azure.com
  ADO_ORG: philip-gai
  ADO_PROJECT: github-ado-chatops
  ADO_REPO: github-ado-chatops
  ADO_PAT: ${{ secrets.ADO_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install and build (skip tests)
        run: |
          npm install
          npm run build --if-present
          # npm run test --if-present
