name: "Azure DevOps ChatOps"

on:
  issue_comment:
    types: [created]

permissions: # GITHUB_TOKEN will have the minimum permissions required to run the ChatOps
  issues: write

jobs:
  run-github-ado-chatops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: philip-gai/github-ado-chatops # you should specify a version here to avoid breaking changes
        with:
          ado_org: philip-gai
          ado_project: github-ado-chatops
          ado_repo: github-ado-chatops
          ado_pat: ${{ secrets.ADO_PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
